### ISSUE TITLE
For the release of v0.1.0-alpha.1 version, task list

### ISSUE THREAD

**Issue by vintagewang** [openmessaging/openmessaging-java#7]
## java doc
- [x] Refactor comments for each method

## dynamically load the specific vendor implement
- [x] URL component definition
- [x] Load the implementation according to the URL
- [x] Check if the specification version matches the implementation version

~~## Message filtering section~~
~~- [ ] support resource management api~~

Postponed to next release.

## exception code & url

- [x] Define OMS internal error code and provide a reference URL

## Promise and Future
- [x] Resolve issue #6 

@vongosling @zhouxinyu @vintagewang  If there are missed task, please add by yourself

**Comment by zhouxinyu** [comment]
## Exception Code & URL

When OpenMessaging internal error occurred, a reference URL will be printed for user:

```java
Exception in thread "main" io.openmessaging.exception.OMSRuntimeException: The OMS driver URL [oms:rocketmq:abcde] is illegal.
For more information, please visit the URL, http://openmessaging.cloud/internal/error-code.html#oms_driver_url_illegal
	at io.openmessaging.internal.MessagingAccessPointAdapter.generateInternalException(MessagingAccessPointAdapter.java:108)
	at io.openmessaging.internal.MessagingAccessPointAdapter.checkDriverURL(MessagingAccessPointAdapter.java:90)
	at io.openmessaging.internal.MessagingAccessPointAdapter.getMessagingAccessPoint(MessagingAccessPointAdapter.java:52)
```

**Comment by zhouxinyu** [comment]
#6 has been resolved, `Promise` now extends `Future`. `Future` is read-only, while `Promise` is writable.

**Comment by zhouxinyu** [comment]
Released!
